/* eslint-disable prettier/prettier */
export const LOGINSUCCESS = "LOGINSUCCESS";
export const LOGINOUTUSER = "LOGINOUTUSERS";
export const SYNCUSERDATA = "SYNCUSERDATA";
export const GETUSERNOTESSUCCESS = "GETUSERNOTESSUCCESS";
export const GETPHOTOGRAPHERSSUCCESS = "GETPHOTOGRAPHERSSUCCESS"
export const GETMYBOOKINGSUCCESS = "GETMYBOOKINGSUCCESS"
export const SETMYLOCATION = "SETMYLOCATION"
